linters-settings:
  goimports:
    local-prefixes: github.com/diogox/bspc-go

linters:
  enable:
    - goimports
    - godot
    - goconst
    - gofumpt
    - govet
    - stylecheck
    - unconvert
    - unparam
    - misspell
    - whitespace
